// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9WH0E8ekZ3BhBZznZREPdmJJQ6wOIqps',
    appId: '1:424510482583:web:905e6c2cf256ab98a361d2',
    messagingSenderId: '424510482583',
    projectId: 'reddit-5b24e',
    authDomain: 'reddit-5b24e.firebaseapp.com',
    storageBucket: 'reddit-5b24e.appspot.com',
    measurementId: 'G-L42BCCF6Z1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZnuvraUneiifp9a5KUqOxLVwFzo__7H8',
    appId: '1:424510482583:android:459cf521f44c379aa361d2',
    messagingSenderId: '424510482583',
    projectId: 'reddit-5b24e',
    storageBucket: 'reddit-5b24e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjIhf5M3H_ckZf5i-PRpXFpjHpTIwKzZo',
    appId: '1:424510482583:ios:dff406a633be6594a361d2',
    messagingSenderId: '424510482583',
    projectId: 'reddit-5b24e',
    storageBucket: 'reddit-5b24e.appspot.com',
    iosClientId: '424510482583-q38a8vdj7sjlmo1okj8hp1oru0f1dc1v.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjIhf5M3H_ckZf5i-PRpXFpjHpTIwKzZo',
    appId: '1:424510482583:ios:dff406a633be6594a361d2',
    messagingSenderId: '424510482583',
    projectId: 'reddit-5b24e',
    storageBucket: 'reddit-5b24e.appspot.com',
    iosClientId: '424510482583-q38a8vdj7sjlmo1okj8hp1oru0f1dc1v.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
